example_project/example_app/urls.py
from django.urls import path

from . import views

app_name = 'example_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('forms', views.forms, name='forms'),
    path('template_tags', views.template_tags, name='template_tags'),
]

example_project/example_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
]

example_project/example_app/models.py
from django.db import models

# Create your models here.

class Fruit(models.Model):
    data = models.JSONField()

    def __str__(self):
        return self.data.get('name', '-')

example_project/example_app/forms.py
from django import forms

from jsonsuit.widgets import JSONSuit, ReadonlyJSONSuit

from .models import Fruit


class FruitForm(forms.ModelForm):
    class Meta:
        model = Fruit
        fields =  '__all__'
        widgets = {
            'data': JSONSuit(),
        }


class ReadonlyFruitForm(forms.ModelForm):
    class Meta:
        model = Fruit
        fields =  '__all__'
        widgets = {
            'data': ReadonlyJSONSuit(),
        }


class RandomJSONForm(forms.Form):
    data = forms.JSONField(widget=JSONSuit())


class RandomReadonlyJSONForm(forms.Form):
    data = forms.JSONField(widget=ReadonlyJSONSuit())

example_project/example_app/views.py
import json, os, requests

from django.conf import settings
from django.shortcuts import render

from .forms import FruitForm, ReadonlyFruitForm, RandomJSONForm, RandomReadonlyJSONForm
from .models import Fruit

# Create your views here.

def index(request):
    return render(request, 'example_app/index.html')    


def template_tags(request):
    with open(os.path.join(settings.BASE_DIR, 'example_app', 'static', 'json_samples', 'fruits.json')) as file:
        data = json.load(file)
    context = {'data': data}
    return render(request, 'example_app/template_tags.html', context)


def forms(request):
    context = {}

    fruit_form = FruitForm(request.POST or None, request.FILES or None, initial=dict(data={}), prefix='editable-fruit')

    if fruit_form.is_valid():
        fruit_form.save()

    context['fruit_form'] = fruit_form
    context['ro_fruit_form'] = ReadonlyFruitForm(instance=Fruit.objects.first(), prefix='readonly-fruit')

    random_json_form = RandomJSONForm(request.POST or None, request.FILES or None, prefix='editable-quote', initial=dict(data={}))

    quote = requests.get('https://dummyjson.com/quotes/random')
    context['random_ro_json_form'] = RandomReadonlyJSONForm(initial=dict(data=quote.json()), prefix='readonly-quote')

    context['random_json_form'] = random_json_form
    return render(request, 'example_app/form.html', context)

example_project/example_app/templates/example_app/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>{% block title %}{% endblock %}</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    {% block styles %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'main.css' %}">
    {% endblock %}
</head>
<body>
    {% block content %}{% endblock content %}
    {% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    {% endblock %}
</body>
</html>

example_project/example_app/templates/example_app/form.html
{% extends "example_app/base.html" %}
{% load admin_urls i18n %}

{% block title %}{% trans "JSONsuit Demo" %}{% endblock %}

{% block styles %}
{{ block.super }}
{{ fruit_form.media.css }}
{{ ro_fruit_form.media.css }}
{% endblock %}

{% block content %}
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto">
        <div class="inner">
            <h3 class="masthead-brand">JSONsuit Example</h3>
            <nav class="nav nav-masthead justify-content-center">
                <a class="nav-link" href="/">Home</a>
                <a class="nav-link" href="{% url 'admin:example_app_fruit_change' 1 %}">Admin</a>
                <a class="nav-link active" href="{% url 'example_app:forms' %}">Forms</a>
                <a class="nav-link" href="{% url 'example_app:template_tags' %}">Template Tags</a>
            </nav>
        </div>
    </header>

    <main role="main" class="inner cover">
        <h1 class="form-heading">Usage with Django (Model)Forms</h1>
        <div class="row">
            <h2>Readonly Form</h2>
            <form class="p-3">
                {% csrf_token %}
                {{ random_ro_json_form.as_div }}
            </form>
        </div>
        <div class="row">
            <h2>Editable Form</h2>
            <form method="POST" class="p-3">
                {% csrf_token %}
                {{ random_json_form.as_div }}
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
        <div class="row">
            <h2>Readonly ModelForm</h2>
            <form class="p-3">
                {% csrf_token %}
                {{ ro_fruit_form.as_div }}
            </form>
        </div>
        <div class="row">
            <h2>Editable ModelForm</h2>
            <form method="POST" class="p-3">
                {% csrf_token %}
                {{ fruit_form.as_div }}
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </main>

    <footer class="mastfoot mt-auto">
        <div class="inner">
            <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a
                    href="https://twitter.com/mdo">@mdo</a>.</p>
        </div>
    </footer>
</div>
{% endblock %}

{% block scripts %}
{{ block.super }}
{{ fruit_form.media.js }}
{{ ro_fruit_form.media.js }}
{% endblock %}

example_project/example_app/templates/example_app/index.html
{% extends "example_app/base.html" %}
{% load admin_urls i18n jsonsuit %}

{% block title %}{% trans "JSONsuit Demo" %}{% endblock %}

{% block styles %}
{{ block.super }}
{% jsonsuit_css %} <!-- include jsonsuit CSS files -->
{% endblock %}

{% block content %}
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto">
    <div class="inner">
        <h3 class="masthead-brand">JSONsuit Example</h3>
        <nav class="nav nav-masthead justify-content-center">
        <a class="nav-link active" href="/">Home</a>
        <a class="nav-link" href="{% url 'admin:example_app_fruit_change' 1 %}">Admin</a>
        <a class="nav-link" href="{% url 'example_app:forms' %}">Forms</a>
        <a class="nav-link" href="{% url 'example_app:template_tags' %}">Template Tags</a>
        </nav>
    </div>
    </header>

    <main role="main" class="inner cover">
    <h1 class="cover-heading">Django goodies to dress JSON data in a suit.</h1>
    <p class="lead">The following sample pages introduce the features of Django JSONsuit and show how to use it with examples.</p>
    <p class="lead">
        <a href="{% url 'admin:example_app_fruit_change' 1 %}" class="btn btn-lg btn-secondary">Admin</a>
        <a href="{% url 'example_app:forms' %}" class="btn btn-lg btn-secondary">Forms</a>
        <a href="{% url 'example_app:template_tags' %}" class="btn btn-lg btn-secondary">Template Tags</a>
    </p>
    </main>

    <footer class="mastfoot mt-auto">
    <div class="inner">
        <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
    </div>
    </footer>
</div>
{% endblock %}

example_project/example_app/templates/example_app/template_tags.html
{% extends "example_app/base.html" %}
{% load jsonsuit i18n %}

{% block title %}{% trans "JSONsuit Demo" %}{% endblock %}

{% block styles %}
{{ block.super }}
{% jsonsuit_css %} <!-- include jsonsuit CSS files -->
{% endblock %}

{% block content %}
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto">
    <div class="inner">
        <h3 class="masthead-brand">JSONsuit Example</h3>
        <nav class="nav nav-masthead justify-content-center">
        <a class="nav-link" href="/">Home</a>
        <a class="nav-link" href="{% url 'admin:example_app_fruit_change' 1 %}">Admin</a>
        <a class="nav-link" href="{% url 'example_app:forms' %}">Forms</a>
        <a class="nav-link active" href="{% url 'example_app:template_tags' %}">Template Tags</a>
        </nav>
    </div>
    </header>

    <main role="main" class="inner cover">
        <div class="p-3 full-width">
            <div class="row">
                <div class="col">
                    <h2>Unnamed Suit</h2>
                    {% jsonsuit data %} <!-- with no parameter supplied,
                                        a uuid is generated as
                                        HTML attribute value to
                                        identify each individual suit:
                                        data-jsonsuit="<uuid>" -->
                </div>
                <div class="col">
                    <h2>Named Suit</h2>
                    {% jsonsuit data 'suit_name' %} <!-- for each suit,
                                                    an optional string
                                                    can be supplied, which
                                                    serves as HTML attribute
                                                    value: data-jsonsuit="<suit_name>" -->
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <h2>Using JSON data from context</h2>
                    {% jsonsuit data %}
                </div>
                <div class="col">
                    <div class="col">
                        <h2>Using inline JSON data</h2>
                        {% jsonsuit '{"key": "value"}' %}
                    </div>
                </div>
            </div>
        </div>
    </main>

    <footer class="mastfoot mt-auto">
    <div class="inner">
        <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
    </div>
    </footer>
</div>
{% endblock %}

{% block scripts %}
{{ block.super }}
{% jsonsuit_js %} <!-- include jsonsuit JS files -->
{% endblock %}